name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.0]

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring
        coverage: none

    - name: Composer
      run: |
        composer install

    - name: Run Pint
      run: ./vendor/bin/pint --test

    - name: Execute tests
      run: php ./compack test
